---
#-------------------------------
# General Site Settings

title: "Shriniwas Sharma"

menu:
  - { name: "Projects", url: "" }
  - { name: "Blog", url: "blog" }
  - { name: "About", url: "about" }
  - { name: "Contact", url: "contact" }

#-------------------------------
# Projects Section

projects:
  - { url: "proj-1", name: "COVID-19 Dashboard for The Netherlands" }
  - { url: "proj-2", name: "COVID-19 Timelapse Visualization" }
  - { url: "proj-3", name: "A Raspberry-Pi based Thermostat" }

#-------------------------------
# Contact Section

social:
  - { icon: "twitter", link: "https://twitter.com/shriniwas172" }
  - { icon: "github", link: "https://github.com/shriniwas26" }
  - { icon: "linkedin", link: "https://linkedin.com/in/shriniwas26" }
  - { icon: "envelope", link: "mailto:mailto:shriniwas26@gmail.com" }

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

# seo:
#   description: 'Personal portfolio powered by Jekyll and GitHub Pages '
#   rel-author: 'https://plus.google.com/u/0/#'
#   rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: ""

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ""
